"""add done

Revision ID: 6766fe08f185
Revises: 53f6f87fc8c0
Create Date: 2017-06-20 00:04:09.087107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6766fe08f185'
down_revision = '53f6f87fc8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
